### ISSUE TITLE
Last Issues to fix before release

### ISSUE THREAD

**Issue by AntonioCarta** [ContinualAI/avalanche#1030]
Guys, we have to fix the last few remaining things before the release. We have divided all the tasks among the core team. Please, try to close these in the next two weeks at most.

@vlomonaco 
- [x] populate list of examples
- [x] create this FAQ
- [x] 5 minutes into a notebook
- [x] General update Avalanche website

@AndreaCossu 
- [x] check apidoc evaluation & loggers
- [x] eval & loggers FZTH

@HamedHemati 
- [x] OCL #967 

**Julio Hurtado**
- [x] check examples

@lrzpellegrini 
- [x] check FZTH: Models, Benchmarks

@ggraffieti 
- [x] check FZTH: Training, putting it all together (if you need help for the training module, ping me).
- [x] optional packaging. Can we make it for the 0.2.0?
- [x] actually push the release?

@AntonioCarta 
- [x] fix the apidoc, adding missing classes, completing the docstrings...
- [x] prepare release statement

**Comment by vlomonaco** [comment]
very good thanks!

**Comment by HamedHemati** [comment]
@AntonioCarta I think you've tagged the wrong person for the examples.

**Comment by AntonioCarta** [comment]
> @AntonioCarta I think you've tagged the wrong person for the examples.

fixed it ;)
