### ISSUE TITLE
Roadmap for 0.3.0

### ISSUE THREAD

**Issue by AntonioCarta** [ContinualAI/avalanche#1203]
I'm opening this issue to keep track of the multiple issues that we have to fix before the next version. Feel free to edit it.

**Features**
- [x] MIR #1201 
- [x] Interactive buffer #1198 
- [x] BiC #1193 
- [ ] Expert Gate #1048 
- [x] fix stream-level metrics #1093 

**Continuous Integration & Tests**

- [x] Check that CLB reach the expected performance for the release version @AndreaCossu 

**Documentation**

- [x] Update dataset notebooks #1146 @AntonioCarta 
- [x] Check apidoc (everyone).
- [x] update notebooks and examples where necessary.

**Comment by AndreaCossu** [comment]
I'll check the evaluation and logging module for the APIdoc and move on to other modules if I finish early.
