### ISSUE TITLE
Avalanche Roadmap to Beta-2 🚀

### ISSUE THREAD

**Issue by vlomonaco** [ContinualAI/avalanche#587]
Here we report a draft roadmap as an **ordered list by features priority** and divided by main modules. This roadmap targets Avalanche **_Beta 2 Release_ (v0.2.0)** set for the **31st of July 2022**.

Bugs are always solved first with maximum priority. New features from the ["Feature Request"](https://github.com/ContinualAI/avalanche/discussions/categories/feature-request) list may be added, but this roadmap keeps track only of the open issues already planned to be integrated for the **Beta Release**! 🚀

**Benchmarks**

- [x] iNaturalist large-scale dataset implementation #298
- [x] Mirroring OpenLoris and Add new link for Auto-Download #617 
- [x] Uniform API for classic Benchmarks #557 
- [x] Change "Scenario" in "Benchmark" Object #503 
- [ ] Fallback mechanism when "targets" is not found #422 
- [ ] Add Doc + Utils to Support Multiple Streams for Benchmark #519 
- [ ] Add Pascal VOC2012 Classic Benchmark #536 
- [ ] Lazy definition of benchmarks #600 
- [ ] Remove task labels for SIT #464 
- [ ] CORe50 Dataset and Benchmark Improvements #547 
- [ ] Integrating the CtRL Benchmark #561 
- [ ] Add Task Descriptors, not only Task Labels #371 
- [ ] Unbalanced Steps Sizes Option for Benchmarks Generators #331 
- [ ] Add MiniImagenet to the Benchmarks #154 

**Evaluation & Logging**

- [x] Confusion Matrix for W&B Evaluation #564 
- [x]  Add summary table [Metrics Name, Brief Description] #585 
- [x] Extend metrics to work with task label at patterns level #647 
- [x] Add TestPlugin to test metrics and other features within callbacks #498
- [x] Add (Lopez-paz, 2017) Metrics: ACC, FWT & BWT #212 

**Models & training**

- [x] Strategies: #527 #274 #4 #85 BiC (@mmasana) (to be updated). New strategies already implemented and tested: ICaRL, PNN, several replay policies.
- [ ] Update Strategy&Plugin API: see discussion in #580 #329 #596 #563 #437 #400 #394 #503
- [ ] Update Documentation (after the API update)

**Continuous Integration & Tests**

- [x] Push notebooks on Colab #381 
- [x] Fix dependencies version #611 
- [x] Add Automatic Docker Release #383 
- [x] Conda & Pi packages #135 
- [ ] Automatic GPU/Deps/Extended tests on VPS #620 

**Documentation**

- [x] Expand FZTH "models" chapter #571 
- [ ] Custom MetricPlugin example #325
- [ ] How-To Tutorials on Gitbook documentation #568 
- [ ] Check Offered Functionalities <-> Doc sync #558 
- [ ] Overall Update of Avalanche Website

**Comment by AndreaCossu** [comment]
Don't we already have the beta project here on github for this purpose?

**Comment by vlomonaco** [comment]
I think it is easier to have a single issue summarizing everything. In the end we don't really use the feature of the "projects" tab. If this works I will close down the projects there but I'm open to suggestions of course.

**Comment by AntonioCarta** [comment]
I agree with @vlomonaco. Roadmap issues are better and they allow for more discussion. I think it's better to close the project to avoid duplication and inconsistent roadmaps.

**Comment by AndreaCossu** [comment]
As long as we keep a single place I'm fine with both. I don't think we would be able to keep the two aligned.

**Comment by AntonioCarta** [comment]
I added some issues about the training API that I would like to tackle before the beta release.

Overall, these is a brief recap of the issues/feedback from the users that I collected over time:

### Requests
- need a simple way to define/customize new strategies #660 
- before/after training semantic #661 
- scenarios' constraints
- some methods are part plugin and part strategy (or more than one of each), it can become more difficult to understand its implementation. The lack of understanding of how some plugins or strategies work can be detrimental since someone can be bypassing the rules/assumptions of some scenarios. #659 
- having one clear way to implement strategies would always make things easier. 
- Having metrics and loggers into plugins makes sense with the name plugins, but having them mixed with the methods and strategies is quite odd to me
- some plugins are not compatible between them.

### CANT/WONT fix
- **experience/scenario reference**: This is in direct contrast with the request for scenarios' constraints and information hiding. Also, at the moment the scenario can be retrieved already from the experience.
- **module independence**: Depending on how you interpret this issue, it's either already solved or unsolvable.
- **override train params (train_epochs, mb_size, ...)** Solved, but in a different way. We can use overriding of strategy methods. Having a single, easy way to customize strategies seems easier than having multiple ways that may be slightly broken when mixed together. See #659 

- [x] custom forward, loss <- these are already implemented
