### ISSUE TITLE
Avalanche Roadmap to Beta-2 (v0.2.0)🚀 

### ISSUE THREAD

**Issue by AntonioCarta** [ContinualAI/avalanche#903]
I'm opening this issue to keep track of the multiple issues that we have to fix before the next version. Feel free to edit it.

**Benchmarks**

- [x] support for object detection (see #547, #536 and #422)
- [ ] Remove task labels for SIT #464 
- [ ] Fallback mechanism when "targets" is not found #422 

**Training**

- [ ] Distributed Training #850 
- [ ] New strategies (which one?)

**Models**

-  [ ] Output masking for SIT and MT

**Continuous Integration & Tests**

- [ ] Automatic GPU/Deps/Extended tests on VPS #620 

**Documentation**
- [ ] Add examples #886 
- [ ] Add JointTraining in FZTH tutorial (see https://github.com/ContinualAI/avalanche/discussions/906)
- [ ] Update docs with new changes (see also #519, #325, https://github.com/ContinualAI/avalanche/pull/902)

**Comment by Harry-Up** [comment]
Thanks for your great work! 

For new strategies, continual learning methods with dynamic network structures may be considered. It avoids catastrophic forgetting by applying different network parts in different tasks. Although this type of method is not elegant, it is simple and effective to avoid forgetting the old task knowledge. Related works include 

- [PiggyBack](https://github.com/arunmallya/piggyback)
- [PackNet](https://github.com/arunmallya/packnet)
- [CPG](https://github.com/ivclab/CPG)
- [RNM](https://gitlab.com/prakhark2/relevance-mapping-networks)
- [HAT](https://github.com/joansj/hat)
- [CCGN](https://github.com/lit-leo/cgate)
- [CCC](https://github.com/ivclab/CondConvContinual)
- ......

**Comment by AndreaCossu** [comment]
Thanks @Harry-Up ! I think most of the features required to build dynamic network structures (and the strategies you mentioned) are already in Avalanche. We just need the bandwidth and time to implement them :smile:

**Comment by niniack** [comment]
Is there a benefit to/thought about adding the ExpertGate approach to Avalanche?

**Comment by AntonioCarta** [comment]
> Is there a benefit to/thought about adding the ExpertGate approach to Avalanche?

yes, we are definitely interested in adding Expert Gates. It should be relatively easy.

**Comment by niniack** [comment]
> yes, we are definitely interested in adding Expert Gates. It should be relatively easy.

It would be nice to give it a shot! If I make it happen, I'll make a PR
